version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: decastro84/my-app
    command: npm start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
